### ISSUE TITLE
SIFT keypoints number and descriptors in fundamental model 

### ISSUE THREAD

**Issue by BruceWangzp** [zjhthu/OANet#11]
I tried to re-train the fundamental model using 8000 sift keypoints. However, using the default setting of in extract_feature.py , only 4000-6000 keypoints can be extracted. And the trained model performed bad compared with provided fundamental estimation model.  Is there any suggestion on the setting of get more points. Thanks~

**Comment by zjhthu** [comment]
It is normal to get less than 8k points.
Which fundamental model do you use? The model trained on GL3D?

**Comment by BruceWangzp** [comment]
Ok, I am using the model trained on yfcc100m.

**Comment by zjhthu** [comment]
This model is trained using `--use_fundamental=True --geo_loss_margin=0.03 --use_ratio=2 --use_mutual=2`. You might need a 24G GPU to train this model, or you need to decrease the batch size and increase training iters.

**Comment by BruceWangzp** [comment]
So it is not the problem of  sift extraction process . Maybe I just forgot to set above parameters. Thanks for your reply.
