### ISSUE TITLE
Lincense and Citations

### ISSUE THREAD

**Issue by kmyid** [zjhthu/OANet#13]
Hi Zixin,

I just noticed that there is a bit of an issue with the license notification and citation acknowledgement for the CVPR 2018 paper. Could you please add them? EPFL and UVic have copyrights to the code and they are only released for research purposes. Thus, you are actually violating it by releasing your code as MIT. Can you please make that part explicit? 

Thanks!
Kwang

**Comment by zjhthu** [comment]
Hi Prof. Kwang,

Sorry for the issue with license and citation.  
For the citation problem, I will explicitly require people to cite the CVPR paper and follow your license if they use the code about data generation, testing, and validation.
For the license problem, currently, I will delete the MIT license and find a more proper one. Do you have any suggestion about the license?

Regards,
Jiahui

**Comment by kmyid** [comment]
Hello Jiahui,

No worries at all. I just thank you a lot for this great work. Anyways, regarding the license, you can do something similar to the ACNe repo, where you explicitly mention which parts are yours, i.e. MIT, and which are EPFL/UVic's I think the ones that have that license already have my header, so I think you can do the same for your files ;)

Cheers,
Kwang

**Comment by zjhthu** [comment]
Hi Kwang,

Thanks for your advice. We have added the UVIC/EPFL license as done in the ACNe repo and updated the readme.

Regards,
Jiahui

**Comment by kmyid** [comment]
Thank you very much
