### ISSUE TITLE
Error 400 when downloading the data

### ISSUE THREAD

**Issue by fdarmon** [zjhthu/OANet#2]
Hi, 
I have successfully downloaded the model however I have a ERROR 400: Bad Request when I try to download the data with `wget https://research.altizure.com/data/oanet_data/data_dump.tar.gz`

Cheers, 
François Darmon

**Comment by zjhthu** [comment]
Should be fine now.
You can run `bash download_data.sh` and then follow the instructions.

Regards,
Jiahui

**Comment by fdarmon** [comment]
It works now, thanks
