### ISSUE TITLE
YFCC100M depth Data

### ISSUE THREAD

**Issue by zwyking** [zjhthu/OANet#20]
hi，
thanks for your great job. Recently, i want to use the dataset of YFCC100M, but i don't find the depth data. while depth.txt exists. Can you tell me how to get the all data

best.

**Comment by zjhthu** [comment]
We also do not have the depth for YFCC. You can run COLMAP to reconstruct the scenes and get the depth.

**Comment by zwyking** [comment]
thanks for your reply. I want to know if the Sun3d Dataset has the depth data original, because i find the depth.txt but don't see the depth file.

**Comment by zjhthu** [comment]
Yes, SUN3D has depth files, but this data is too large to find a proper way to upload. You can download it from the original [site](http://sun3d.cs.princeton.edu/) using this [tool](https://github.com/PrincetonVision/SUN3DCppReader).

**Comment by atztao** [comment]
> Yes, SUN3D has depth files, but this data is too large to find a proper way to upload. You can download it from the original [site](http://sun3d.cs.princeton.edu/) using this [tool](https://github.com/PrincetonVision/SUN3DCppReader).

Hey, the keypoint match of the ground-truth in your paper used this depth information or just used the BFmatch?

**Comment by zjhthu** [comment]
The ground-truth is computed using [geometric distance](https://github.com/zjhthu/OANet/blob/master/dump_match/sequence.py#L110l).  [Positive matches](https://github.com/zjhthu/OANet/blob/master/core/loss.py#L61) are those whos geometric distance is small.

**Comment by atztao** [comment]
> The ground-truth is computed using [geometric distance](https://github.com/zjhthu/OANet/blob/master/dump_match/sequence.py#L110l). [Positive matches](https://github.com/zjhthu/OANet/blob/master/core/loss.py#L61) are those whos geometric distance is small.

Thanks.
