### ISSUE TITLE
The test pre-training model is inconsistent with the paper on the yfcc

### ISSUE THREAD

**Issue by fantuslk** [zjhthu/OANet#22]
![oanet_test](https://user-images.githubusercontent.com/44725521/112111670-7b7a7680-8bef-11eb-959a-e47c89b4207e.PNG)
It is the downloaded code and data, without any modification.

**Comment by zjhthu** [comment]
mAP5° results are saved separately in the log dir. The printed results are mAP 20°

**Comment by fantuslk** [comment]
Hi zjhthu,
Is the result of mAP5° recorded in acc_qt_auc_5_ours.txt?corresponding to the last unknown without ransac in Table 2 of the paper 39.33?

**Comment by zjhthu** [comment]
yes

**Comment by fantuslk** [comment]
Well, thank you for your guidance.
