### ISSUE TITLE
geometry loss in the paper and epipolar loss use in the code

### ISSUE THREAD

**Issue by fantuslk** [zjhthu/OANet#24]
Hi,
why is the code implementation inconsistent with the paper...

**Comment by fantuslk** [comment]
![2](https://user-images.githubusercontent.com/44725521/118217419-ffdace80-b4a7-11eb-86f1-35eaaa7bfbca.JPG)
in the paper
![1](https://user-images.githubusercontent.com/44725521/118217433-0701dc80-b4a8-11eb-8e27-e4e5a6802cd2.JPG)
in the code

**Comment by zjhthu** [comment]
Good point! The former is sampson error which the latter is symmetrical epipolar distance. There should be no significant difference, both are ok.
