### ISSUE TITLE
How to calculate mAP via the results?

### ISSUE THREAD

**Issue by olivercho98** [zjhthu/OANet#26]
Excuse me, I have run the code and get result saved as shown in the image.
![AAD5167F-4203-4037-8053-AEEFDE7B6424](https://user-images.githubusercontent.com/39474380/142186658-2bb6a6cd-adca-4ac8-bb96-be4b3fc7cbcf.png)
I was wondering how to calculate mAP in the paper via these AUC results.

Thank you,

**Comment by zjhthu** [comment]
mAP5 is the result in acc_qt_acu5*.txt.

**Comment by olivercho98** [comment]
okay, thanks for the response.
