### ISSUE TITLE
Hello author, I have a question for you about the YFCC100M dataset

### ISSUE THREAD

**Issue by MnYangs** [zjhthu/OANet#32]
The link you provided to download the raw_data_yfcc.tar.gz file is not working. The reason should be that altizure platform is closed. Do you have any other downloading methods?

I look forward to your reply. Thank you.

**Comment by zjhthu** [comment]
Sorry for the downloading. I will back up a copy of the data on Google Drive in this week. I will notify you after finishing this job.

**Comment by MnYangs** [comment]
Thank you for your help and look forward to your data set being uploaded successfully.

**Comment by zjhthu** [comment]
Hi, here is the link to the data and model, https://drive.google.com/drive/folders/1qbnrDSXJhnXC0MiZNNqW7vezAHlkBNgo?usp=sharing. You can have a try.
