### ISSUE TITLE
how to load contextdesc model?

### ISSUE THREAD

**Issue by tomjerrygithub** [zjhthu/OANet#4]
when i  use contextdesc-yfcc model in the demo script  
self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for OANet:
	size mismatch for weights_init.conv1.weight: copying a param with shape torch.Size([128, 5, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 4, 1, 1]).
	size mismatch for weights_iter.0.conv1.weight: copying a param with shape torch.Size([128, 7, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 6, 1, 1]).

how to use the contextdesc model ? thanks

**Comment by zjhthu** [comment]
You need to set `use_ratio=2, use_mutual=0` to use the ContextDesc model. Unfortunately, the current code does not support this mode, we will fix this later. 

By the way, the demo is only for fundamental matrix estimation, but the provided ContextDesc model is for essential matrix estimation, you need to provide camera intrinsics when using this model.

**Comment by tomjerrygithub** [comment]
Thank you. 
If I want to use oanet for AR, are there any good suggestions? I currently use “sift” + “Learning to Find Good Correspondences ” to find matching points and then calculate homography matrix. But the video scene is usually not coplanar, so the effect is poor.

**Comment by zjhthu** [comment]
Both _learning corr_ and our work are trained for essential or fundamental matrix estimation. Models trained for essential matrix certainly have poor generalization ability in homography matrix estimation.

If you want a homography matrix estimation model, you need to train it using homography data. If you want to use the model in both homography and fundamental cases, you should modify the network or training setting, _e.g._, remove the geometry loss or use different solvers for these two cases.

You can train OANet without geometry loss on your own data. If you want it to work on homography case, you also need to collect homography data. Set `--use_fundamental=True` if you do not have camera intrinsics.

**Comment by tomjerrygithub** [comment]
i have no  camera intrinsics ，can i use a default intrinsics to  use fundamental matix ? 

and another question  how to " Together with the local feature ContextDesc "  to use OANet ?

**Comment by zjhthu** [comment]
If you have no camera intrinsics, you can just use the fundamental matrix estimation model, which is shown in our demo. 
To use ContextDesc, you can have a look at the [original repo](https://github.com/lzx551402/contextdesc).
We might give more detailed instructions and more models later. Sorry that I do not have enough time to do these things recently.

**Comment by tomjerrygithub** [comment]
thanks much ，i will try

**Comment by zjhthu** [comment]
Now the code supports `use_ratio=2`. You can test the ContextDesc model following the instruction in README.
Currently, I only have an essential matrix estimation model for ContextDesc, but the demo needs a fundamental matrix estimation model. So the uploaded ContextDesc model can not be directly used in the demo scripts. You can train a fundamental matrix estimation model yourself in your own application.
