### ISSUE TITLE
where is yfcc_train.txt?

### ISSUE THREAD

**Issue by passion3394** [zjhthu/OANet#5]
firstly, thanks for your great work. But when I have downloaded the YFCC100M dataset, and I try to generate the yfcc dataset, I can not find the yfcc_train.txt in this dataset.

`# dump yfcc training seqs
    with open('yfcc_train.txt','r') as ofp:
        train_seqs = ofp.read().split('\n')
    if len(train_seqs[-1]) == 0:
        del train_seqs[-1]`

**Comment by zjhthu** [comment]
it is just in the repo
https://github.com/zjhthu/OANet/blob/master/dump_match/yfcc_train.txt

**Comment by passion3394** [comment]
found it.
