### ISSUE TITLE
if I want to train my own dataset

### ISSUE THREAD

**Issue by passion3394** [zjhthu/OANet#6]
thanks ahead. I have read your preprocessing code on the yfcc dataset, but I do not understand the process of it. Now If I want to do the feature matching on my own dataset, what steps should I do?

**Comment by zjhthu** [comment]
which do you want? Training or testing on your own dataset? If just testing, you can follow the code provided in the demo. If training, you had better prepare your dataset as the provided YFCC dataset. You need intrinsics, camera pose for each image and visibility to check which pair can be matched.

**Comment by passion3394** [comment]
@zjhthu I don't have the intrisics, camera pose, I already prepared the matched pair of images.

**Comment by zjhthu** [comment]
Intrinsics and camera poses are must required for training. You can run 3D reconstruction software such as COLMAP to generate reconstructions for your scenes and then parsing the result files to get these information.

**Comment by passion3394** [comment]
@zjhthu thanks for your suggestion. I will try to use colmap to generate intrisics and extrinsics.

**Comment by passion3394** [comment]
BTW, I cannot find the preprocessing details from your paper, is there any docs about that?

especially for the following code:
`def make_xy(self, ii, jj):
        geom_i, geom_j = parse_geom(self.geom[ii]), parse_geom(self.geom[jj])
        # should check the image size here
        #load img and check img_size
        image_i, image_j = self.image_fullpath_list[ii], self.image_fullpath_list[jj]
        kp_i = loadh5(image_i+'.'+self.desc_name+'.hdf5')["keypoints"][:, :2]
        kp_j = loadh5(image_j+'.'+self.desc_name+'.hdf5')["keypoints"][:, :2]
        cx1, cy1, f1 = self.unpack_K(geom_i)
        cx2, cy2, f2 = self.unpack_K(geom_j) 
        x1 = self.norm_kp(cx1, cy1, f1[0], f1[1], kp_i)
        x2 = self.norm_kp(cx2, cy2, f2[0], f2[1], kp_j)
        R_i, R_j = geom_i["R"], geom_j["R"]
        dR = np.dot(R_j, R_i.T)
        t_i, t_j = geom_i["t"].reshape([3, 1]), geom_j["t"].reshape([3, 1])
        dt = t_j - np.dot(dR, t_i)
        if np.sqrt(np.sum(dt**2)) <= 1e-5:
            return []
        dtnorm = np.sqrt(np.sum(dt**2))
        dt /= dtnorm
        nn_info = loadh5(os.path.join(self.intermediate_dir, "nn-{}-{}.h5".format(ii, jj)))
        idx_sort, ratio_test, mutual_nearest = nn_info["idx_sort"], nn_info["ratio_test"], nn_info["mutual_nearest"]
        x2 = x2[idx_sort[1],:]
        xs = np.concatenate([x1, x2], axis=1).reshape(1,-1,4)
        geod_d = get_episym(x1, x2, dR, dt)
        ys = geod_d.reshape(-1,1)
        return xs, ys, dR, dt, ratio_test, mutual_nearest, cx1, cy1, f1, cx2, cy2, f2`

**Comment by zjhthu** [comment]
these code are used for generating training and testing data. it loads pre-saved information (intrinsics, extrinsic, descriptors) to compute matches, side information, geometric error and etc. 

currently, we do not have docs about the data format. but you can understand it by exploring the provided yfcc data and code. we may improve it later.

**Comment by ameliamlz** [comment]
@passion3394 have you finished create your own dataset?if you do,can you tell me the specific steps?

**Comment by passion3394** [comment]
@ameliamlz I didn't try the method then.

**Comment by ameliamlz** [comment]
@passion3394 oh.thank you

**Comment by ameliamlz** [comment]
@zjhthu dear author,thanks your project very much.i also have a question about my own dataset.if i want to train with my data,what do i need to prepare?or specially,which files i need to prepare?can you give me a special answer?

**Comment by zjhthu** [comment]
As mentioned above, you need intrinsics and camera poses for image pairs. You can download the YFCC100M dataset to see how we organize these files.

**Comment by ameliamlz** [comment]
@zjhthu ok.Although i want to know more,thank you.

**Comment by ameliamlz** [comment]
@zjhthu do you know the numbers in file 'raw_data/yfcc100m/big_ben_1/train/visibility/vis_000001.txt' means what?

**Comment by zjhthu** [comment]
visibility is a metric to determine which pair is matchable, such as the overlap of image pairs or shared visible 3d points.

**Comment by ameliamlz** [comment]
@zjhthu so the highest  number of the file means a kind of score that represent which image is the most matchable one?

**Comment by zjhthu** [comment]
yes

**Comment by ameliamlz** [comment]
@zjhthu ok .thank you very much

**Comment by LiuJinxue** [comment]
Hi @zjhthu,   if i train the model on the GL3D, should I transform the K. 
Because there is commend "# assert(abs(K[0, 2]) < 1e-3 and abs(K[1, 2]) < 1e-3)".  so how should I preprocess K for the GL3D data.

**Comment by zjhthu** [comment]
yes if you want to keep the code unchanged

**Comment by BetterG** [comment]
@zjhthu Thanks for your code. I want to make my own dataset on indoor dataset and I need to compute the visibility. In your paper I saw that "The visual overlap for indoor scenes is computed by projecting the depth map to the other image". Could you be more specific and provide the code about computing visibility?

**Comment by zjhthu** [comment]
Previous we just simply project the depth map to another image and count overlapping pixels.  This method is fast but it can not handle occlusion, so there might be images that can not be matched.

Compute the overlap using point clouds of two images can be a better way.

**Comment by BetterG** [comment]
@zjhthu OK. Thank you.

**Comment by ameliamlz** [comment]
@zjhthu i only found 'ys' is used in sequence.py and geom.py,but i don't know where to use them.Can you tell me how to produce 'ys' by correspondence(xs)? I only need know the relation between them.

**Comment by zjhthu** [comment]
'ys' is used in [loss computation](https://github.com/zjhthu/OANet/blob/master/core/loss.py#L28). 
It is generated by [geometry distance](https://github.com/zjhthu/OANet/blob/master/dump_match/sequence.py#L110).

**Comment by ameliamlz** [comment]
@zjhthu thank you very much

**Comment by ameliamlz** [comment]
@zjhthu if my dataset doesn't have this file 'visibility',and i run main.py and demo.py. the model runs so bad,can you help me analysis the reason?
